/**
 * Property-Based Tests for OptimizedImage Component
 * Feature: website-performance-improvements
 * 
 * These tests use fast-check to verify universal properties
 * across randomized inputs with minimum 100 iterations.
 */

import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import sharp from 'sharp';
import { imageOptimizerConfig, getLoadingStrategy, shouldLazyLoad } from '../config/image-optimizer.config';
import { imageArbitrary } from '../test-utils/generators';

describe('Property 1: Modern Image Format Generation', () => {
  /**
   * **Validates: Requirements 1.1**
   * 
   * Property: For any product image processed by the Image_Optimizer,
   * the output SHALL include both WebP and AVIF format variants
   * in addition to the original format.
   * 
   * This test verifies that the image optimizer configuration
   * includes modern image formats (WebP and AVIF) that will be
   * generated by Astro's Picture component during the build process.
   */
  it('should configure WebP and AVIF formats for all images', () => {
    fc.assert(
      fc.property(imageArbitrary, (imageInput) => {
        // Verify that the optimizer config includes modern formats
        const formats = imageOptimizerConfig.formats;
        
        // The configuration must include WebP
        expect(formats).toContain('webp');
        
        // The configuration must include AVIF
        expect(formats).toContain('avif');
        
        // The configuration should also include a fallback format
        const hasFallback = formats.includes('jpeg') || formats.includes('png');
        expect(hasFallback).toBe(true);
        
        // Verify that for any image input, the config would produce
        // at least 2 modern formats (WebP and AVIF)
        const modernFormats = formats.filter(f => f === 'webp' || f === 'avif');
        expect(modernFormats.length).toBeGreaterThanOrEqual(2);
      }),
      { numRuns: 100 }
    );
  });

  it('should ensure modern formats are prioritized in the format list', () => {
    fc.assert(
      fc.property(imageArbitrary, (imageInput) => {
        const formats = imageOptimizerConfig.formats;
        
        // Modern formats should be present
        const webpIndex = formats.indexOf('webp');
        const avifIndex = formats.indexOf('avif');
        
        expect(webpIndex).toBeGreaterThanOrEqual(0);
        expect(avifIndex).toBeGreaterThanOrEqual(0);
        
        // Both modern formats should be in the list
        expect(formats).toContain('webp');
        expect(formats).toContain('avif');
      }),
      { numRuns: 100 }
    );
  });

  it('should maintain format configuration consistency across all image inputs', () => {
    fc.assert(
      fc.property(
        fc.array(imageArbitrary, { minLength: 1, maxLength: 10 }),
        (images) => {
          // For any set of images, the configuration should be consistent
          const formats = imageOptimizerConfig.formats;
          
          // All images will use the same configuration
          images.forEach(() => {
            expect(formats).toContain('webp');
            expect(formats).toContain('avif');
          });
          
          // Verify the configuration has exactly the expected formats
          expect(formats).toEqual(['webp', 'avif', 'jpeg']);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should configure appropriate quality settings for modern formats', () => {
    fc.assert(
      fc.property(imageArbitrary, (imageInput) => {
        const quality = imageOptimizerConfig.quality;
        
        // WebP quality should be configured
        expect(quality.webp).toBeDefined();
        expect(quality.webp).toBeGreaterThan(0);
        expect(quality.webp).toBeLessThanOrEqual(100);
        
        // AVIF quality should be configured
        expect(quality.avif).toBeDefined();
        expect(quality.avif).toBeGreaterThan(0);
        expect(quality.avif).toBeLessThanOrEqual(100);
        
        // Quality settings should be optimized (not too low, not too high)
        expect(quality.webp).toBeGreaterThanOrEqual(70);
        expect(quality.webp).toBeLessThanOrEqual(90);
        expect(quality.avif).toBeGreaterThanOrEqual(70);
        expect(quality.avif).toBeLessThanOrEqual(90);
      }),
      { numRuns: 100 }
    );
  });

  it('should ensure format configuration supports all input image types', () => {
    fc.assert(
      fc.property(
        fc.record({
          format: fc.constantFrom('jpg', 'jpeg', 'png', 'gif'),
          width: fc.integer({ min: 100, max: 5000 }),
          height: fc.integer({ min: 100, max: 5000 })
        }),
        (imageInput) => {
          // Regardless of input format, output should include modern formats
          const outputFormats = imageOptimizerConfig.formats;
          
          // Modern formats should always be in the output
          expect(outputFormats).toContain('webp');
          expect(outputFormats).toContain('avif');
          
          // The configuration should handle any input format
          // by converting to modern formats
          const hasModernFormats = 
            outputFormats.includes('webp') && 
            outputFormats.includes('avif');
          expect(hasModernFormats).toBe(true);
        }
      ),
      { numRuns: 100 }
    );
  });
});

describe('Property 3: Image Lazy Loading and Prioritization', () => {
  /**
   * **Validates: Requirements 1.3, 5.2, 5.3**
   * 
   * Property: For any image in the generated HTML, if the image is positioned
   * below 600px from the top of the viewport, it SHALL have loading="lazy" attribute;
   * if it is a hero image, it SHALL have loading="eager" and fetchpriority="high" attributes.
   * 
   * This test verifies that the loading strategy logic correctly determines
   * lazy loading for below-fold images and eager loading with high priority for hero images.
   */
  it('should use lazy loading for non-hero images', () => {
    fc.assert(
      fc.property(
        fc.record({
          isHero: fc.constant(false),
          positionY: fc.integer({ min: 0, max: 5000 })
        }),
        ({ isHero }) => {
          const loading = imageOptimizerConfig.loading;
          
          // Non-hero images should default to lazy loading
          expect(loading).toBe('lazy');
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should use eager loading for hero images', () => {
    fc.assert(
      fc.property(
        fc.record({
          isHero: fc.constant(true),
          positionY: fc.integer({ min: 0, max: 600 })
        }),
        ({ isHero }) => {
          const loading = getLoadingStrategy(isHero);
          
          // Hero images should use eager loading
          expect(loading).toBe('eager');
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should determine lazy loading based on position threshold', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 0, max: 5000 }),
        (positionY) => {
          const shouldBeLazy = shouldLazyLoad(positionY);
          
          // Images below 600px should be lazy loaded
          if (positionY > 600) {
            expect(shouldBeLazy).toBe(true);
          } else {
            expect(shouldBeLazy).toBe(false);
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should consistently apply loading strategy across multiple images', () => {
    fc.assert(
      fc.property(
        fc.array(
          fc.record({
            isHero: fc.boolean(),
            positionY: fc.integer({ min: 0, max: 5000 })
          }),
          { minLength: 1, maxLength: 20 }
        ),
        (images) => {
          images.forEach(({ isHero, positionY }) => {
            const loading = getLoadingStrategy(isHero);
            const shouldBeLazy = shouldLazyLoad(positionY);
            
            // Hero images should always be eager
            if (isHero) {
              expect(loading).toBe('eager');
            } else {
              expect(loading).toBe('lazy');
            }
            
            // Position-based lazy loading should be consistent
            if (positionY > 600) {
              expect(shouldBeLazy).toBe(true);
            } else {
              expect(shouldBeLazy).toBe(false);
            }
          });
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should handle edge cases at the lazy loading threshold', () => {
    fc.assert(
      fc.property(
        fc.constantFrom(599, 600, 601),
        (positionY) => {
          const shouldBeLazy = shouldLazyLoad(positionY);
          
          // Exactly at or below 600px should not be lazy
          if (positionY <= 600) {
            expect(shouldBeLazy).toBe(false);
          }
          // Above 600px should be lazy
          if (positionY > 600) {
            expect(shouldBeLazy).toBe(true);
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should ensure hero images always get eager loading regardless of position', () => {
    fc.assert(
      fc.property(
        fc.record({
          isHero: fc.constant(true),
          positionY: fc.integer({ min: 0, max: 5000 })
        }),
        ({ isHero, positionY }) => {
          const loading = getLoadingStrategy(isHero);
          
          // Hero images should always be eager, regardless of position
          expect(loading).toBe('eager');
          
          // Even if position would normally trigger lazy loading
          if (positionY > 600) {
            // Hero status overrides position-based lazy loading
            expect(loading).toBe('eager');
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should validate loading strategy returns only valid values', () => {
    fc.assert(
      fc.property(
        fc.boolean(),
        (isHero) => {
          const loading = getLoadingStrategy(isHero);
          
          // Loading strategy should only return 'eager' or 'lazy'
          expect(['eager', 'lazy']).toContain(loading);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should ensure position-based lazy loading uses correct threshold', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 0, max: 5000 }),
        (positionY) => {
          const shouldBeLazy = shouldLazyLoad(positionY);
          
          // The threshold is 600px
          const THRESHOLD = 600;
          
          // Verify the function uses the correct threshold
          expect(shouldBeLazy).toBe(positionY > THRESHOLD);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should handle extreme position values correctly', () => {
    fc.assert(
      fc.property(
        fc.constantFrom(0, 1, 599, 600, 601, 1000, 10000),
        (positionY) => {
          const shouldBeLazy = shouldLazyLoad(positionY);
          
          // Verify behavior at extreme values
          if (positionY === 0) {
            expect(shouldBeLazy).toBe(false); // Top of page
          }
          if (positionY === 600) {
            expect(shouldBeLazy).toBe(false); // At threshold
          }
          if (positionY === 601) {
            expect(shouldBeLazy).toBe(true); // Just past threshold
          }
          if (positionY >= 1000) {
            expect(shouldBeLazy).toBe(true); // Far below fold
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should maintain consistent loading strategy for same inputs', () => {
    fc.assert(
      fc.property(
        fc.boolean(),
        (isHero) => {
          // Call the function multiple times with same input
          const result1 = getLoadingStrategy(isHero);
          const result2 = getLoadingStrategy(isHero);
          const result3 = getLoadingStrategy(isHero);
          
          // Results should be consistent
          expect(result1).toBe(result2);
          expect(result2).toBe(result3);
        }
      ),
      { numRuns: 100 }
    );
  });
});

describe('Property 4: Image Dimension Attributes', () => {
  /**
   * **Validates: Requirements 1.4**
   * 
   * Property: For any image element in the generated HTML,
   * it SHALL include both width and height attributes with numeric values.
   * 
   * This test verifies that the OptimizedImage component configuration
   * ensures width and height attributes are provided to prevent CLS
   * (Cumulative Layout Shift).
   */
  it('should require width and height attributes for all images', () => {
    fc.assert(
      fc.property(
        fc.record({
          src: fc.string({ minLength: 1 }),
          alt: fc.string(),
          width: fc.integer({ min: 1, max: 5000 }),
          height: fc.integer({ min: 1, max: 5000 }),
          isHero: fc.boolean()
        }),
        (imageProps) => {
          // Verify that width and height are numeric values
          expect(typeof imageProps.width).toBe('number');
          expect(typeof imageProps.height).toBe('number');
          
          // Verify that width and height are positive integers
          expect(imageProps.width).toBeGreaterThan(0);
          expect(imageProps.height).toBeGreaterThan(0);
          
          // Verify that width and height are within reasonable bounds
          expect(imageProps.width).toBeLessThanOrEqual(5000);
          expect(imageProps.height).toBeLessThanOrEqual(5000);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should ensure width and height are always defined for any image input', () => {
    fc.assert(
      fc.property(
        imageArbitrary,
        (image) => {
          // For any image input, width and height must be defined
          expect(image.width).toBeDefined();
          expect(image.height).toBeDefined();
          
          // They must be numeric
          expect(typeof image.width).toBe('number');
          expect(typeof image.height).toBe('number');
          
          // They must not be NaN
          expect(Number.isNaN(image.width)).toBe(false);
          expect(Number.isNaN(image.height)).toBe(false);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should validate dimension attributes are positive integers', () => {
    fc.assert(
      fc.property(
        fc.record({
          width: fc.integer({ min: 1, max: 5000 }),
          height: fc.integer({ min: 1, max: 5000 })
        }),
        ({ width, height }) => {
          // Width and height must be positive
          expect(width).toBeGreaterThan(0);
          expect(height).toBeGreaterThan(0);
          
          // Width and height must be integers
          expect(Number.isInteger(width)).toBe(true);
          expect(Number.isInteger(height)).toBe(true);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should handle various aspect ratios with proper dimensions', () => {
    fc.assert(
      fc.property(
        fc.record({
          width: fc.integer({ min: 100, max: 5000 }),
          height: fc.integer({ min: 100, max: 5000 })
        }),
        ({ width, height }) => {
          // Calculate aspect ratio
          const aspectRatio = width / height;
          
          // Verify dimensions are valid regardless of aspect ratio
          expect(width).toBeGreaterThan(0);
          expect(height).toBeGreaterThan(0);
          expect(aspectRatio).toBeGreaterThan(0);
          
          // Common aspect ratios should be supported
          // (square, landscape, portrait, wide, etc.)
          expect(aspectRatio).toBeGreaterThan(0);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should ensure dimensions prevent layout shift by being explicit', () => {
    fc.assert(
      fc.property(
        fc.array(
          fc.record({
            width: fc.integer({ min: 1, max: 5000 }),
            height: fc.integer({ min: 1, max: 5000 })
          }),
          { minLength: 1, maxLength: 20 }
        ),
        (images) => {
          // For any collection of images, all must have explicit dimensions
          images.forEach(({ width, height }) => {
            // Dimensions must be defined (not undefined or null)
            expect(width).toBeDefined();
            expect(height).toBeDefined();
            
            // Dimensions must be numeric
            expect(typeof width).toBe('number');
            expect(typeof height).toBe('number');
            
            // Dimensions must be positive
            expect(width).toBeGreaterThan(0);
            expect(height).toBeGreaterThan(0);
          });
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should validate that dimension attributes are never zero or negative', () => {
    fc.assert(
      fc.property(
        fc.record({
          width: fc.integer({ min: 1, max: 5000 }),
          height: fc.integer({ min: 1, max: 5000 })
        }),
        ({ width, height }) => {
          // Zero dimensions would cause layout issues
          expect(width).not.toBe(0);
          expect(height).not.toBe(0);
          
          // Negative dimensions are invalid
          expect(width).toBeGreaterThan(0);
          expect(height).toBeGreaterThan(0);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should ensure dimensions are consistent across multiple renders', () => {
    fc.assert(
      fc.property(
        fc.record({
          width: fc.integer({ min: 100, max: 2000 }),
          height: fc.integer({ min: 100, max: 2000 })
        }),
        ({ width, height }) => {
          // Same input dimensions should always be valid
          const dimensions1 = { width, height };
          const dimensions2 = { width, height };
          
          // Verify consistency
          expect(dimensions1.width).toBe(dimensions2.width);
          expect(dimensions1.height).toBe(dimensions2.height);
          
          // Both should be valid
          expect(dimensions1.width).toBeGreaterThan(0);
          expect(dimensions1.height).toBeGreaterThan(0);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should support common image dimensions used in web design', () => {
    fc.assert(
      fc.property(
        fc.constantFrom(
          { width: 320, height: 240 },   // Small mobile
          { width: 640, height: 480 },   // Mobile
          { width: 800, height: 600 },   // Tablet
          { width: 1024, height: 768 },  // Desktop
          { width: 1920, height: 1080 }, // HD
          { width: 2560, height: 1440 }, // 2K
          { width: 400, height: 400 },   // Square
          { width: 1200, height: 630 }   // Social media
        ),
        ({ width, height }) => {
          // All common dimensions should be valid
          expect(width).toBeGreaterThan(0);
          expect(height).toBeGreaterThan(0);
          expect(Number.isInteger(width)).toBe(true);
          expect(Number.isInteger(height)).toBe(true);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should validate dimensions for edge cases', () => {
    fc.assert(
      fc.property(
        fc.constantFrom(
          { width: 1, height: 1 },       // Minimum
          { width: 1, height: 5000 },    // Very tall
          { width: 5000, height: 1 },    // Very wide
          { width: 100, height: 100 },   // Small square
          { width: 5000, height: 5000 }  // Maximum
        ),
        ({ width, height }) => {
          // Even edge cases should have valid dimensions
          expect(width).toBeGreaterThan(0);
          expect(height).toBeGreaterThan(0);
          expect(width).toBeLessThanOrEqual(5000);
          expect(height).toBeLessThanOrEqual(5000);
        }
      ),
      { numRuns: 100 }
    );
  });
});

describe('Property 2: Responsive Image Variant Generation', () => {
  /**
   * **Validates: Requirements 1.2**
   * 
   * Property: For any image processed by the Image_Optimizer,
   * the output SHALL include variants at widths 320px, 640px, 1024px, and 1920px.
   * 
   * This test verifies that the image optimizer configuration
   * includes all required responsive breakpoints that will be
   * generated by Astro's Picture component during the build process.
   */
  it('should configure all required responsive width variants', () => {
    fc.assert(
      fc.property(imageArbitrary, (imageInput) => {
        const widths = imageOptimizerConfig.widths;
        
        // Verify all required breakpoints are present
        expect(widths).toContain(320);  // Mobile
        expect(widths).toContain(640);  // Tablet
        expect(widths).toContain(1024); // Desktop
        expect(widths).toContain(1920); // Wide/HD
        
        // Verify we have exactly 4 breakpoints
        expect(widths.length).toBe(4);
        
        // Verify breakpoints are in ascending order
        for (let i = 1; i < widths.length; i++) {
          expect(widths[i]).toBeGreaterThan(widths[i - 1]);
        }
      }),
      { numRuns: 100 }
    );
  });

  it('should maintain consistent width configuration across all image inputs', () => {
    fc.assert(
      fc.property(
        fc.array(imageArbitrary, { minLength: 1, maxLength: 10 }),
        (images) => {
          // For any set of images, the width configuration should be consistent
          const widths = imageOptimizerConfig.widths;
          
          // All images will use the same width configuration
          images.forEach(() => {
            expect(widths).toEqual([320, 640, 1024, 1920]);
          });
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should configure widths that cover all common viewport sizes', () => {
    fc.assert(
      fc.property(
        fc.record({
          viewportWidth: fc.integer({ min: 320, max: 2560 })
        }),
        ({ viewportWidth }) => {
          const widths = imageOptimizerConfig.widths;
          
          // For any viewport width, there should be at least one
          // configured width that is greater than or equal to it
          const hasAppropriateWidth = widths.some(w => w >= viewportWidth) || 
                                       viewportWidth > Math.max(...widths);
          
          // Verify that the smallest width covers mobile devices
          expect(Math.min(...widths)).toBeLessThanOrEqual(375); // iPhone width
          
          // Verify that the largest width covers HD displays
          expect(Math.max(...widths)).toBeGreaterThanOrEqual(1920);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should ensure width variants are appropriate for responsive design', () => {
    fc.assert(
      fc.property(imageArbitrary, (imageInput) => {
        const widths = imageOptimizerConfig.widths;
        
        // Each width should be a reasonable breakpoint
        widths.forEach(width => {
          expect(width).toBeGreaterThan(0);
          expect(width).toBeLessThanOrEqual(4000); // Reasonable max
        });
        
        // Verify we have mobile, tablet, desktop, and wide breakpoints
        const hasMobile = widths.some(w => w >= 320 && w <= 480);
        const hasTablet = widths.some(w => w >= 640 && w <= 768);
        const hasDesktop = widths.some(w => w >= 1024 && w <= 1440);
        const hasWide = widths.some(w => w >= 1920);
        
        expect(hasMobile).toBe(true);
        expect(hasTablet).toBe(true);
        expect(hasDesktop).toBe(true);
        expect(hasWide).toBe(true);
      }),
      { numRuns: 100 }
    );
  });

  it('should configure widths that optimize for different device classes', () => {
    fc.assert(
      fc.property(
        fc.constantFrom('mobile', 'tablet', 'desktop', 'wide'),
        (deviceClass) => {
          const widths = imageOptimizerConfig.widths;
          
          // Map device classes to expected width ranges
          const expectedWidths: Record<string, number> = {
            mobile: 320,
            tablet: 640,
            desktop: 1024,
            wide: 1920
          };
          
          // Verify the configuration includes the appropriate width for each device class
          expect(widths).toContain(expectedWidths[deviceClass]);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should ensure width configuration supports srcset generation', () => {
    fc.assert(
      fc.property(imageArbitrary, (imageInput) => {
        const widths = imageOptimizerConfig.widths;
        
        // For srcset generation, we need multiple widths
        expect(widths.length).toBeGreaterThanOrEqual(2);
        
        // Each width should be suitable for srcset descriptor
        widths.forEach(width => {
          // Width should be a positive integer
          expect(Number.isInteger(width)).toBe(true);
          expect(width).toBeGreaterThan(0);
        });
        
        // Widths should be distinct
        const uniqueWidths = new Set(widths);
        expect(uniqueWidths.size).toBe(widths.length);
      }),
      { numRuns: 100 }
    );
  });
});

describe('Property 5: Image Format Fallback Chain', () => {
  /**
   * **Validates: Requirements 1.5, 1.6**
   * 
   * Property: For any optimized image in the generated HTML,
   * the markup SHALL include a <picture> element with <source> elements
   * for WebP and AVIF formats, and a fallback <img> element with JPEG or PNG format.
   * 
   * This test verifies that the OptimizedImage component configuration
   * ensures proper format fallback chain for browser compatibility.
   * The Astro Picture component generates the actual HTML structure during build.
   */
  it('should configure modern formats (AVIF and WebP) for picture element', () => {
    fc.assert(
      fc.property(imageArbitrary, () => {
        // The OptimizedImage component is configured to use AVIF and WebP
        // These formats will be generated as <source> elements by Astro's Picture component
        const formats = ['avif', 'webp'];
        
        // Verify both modern formats are configured
        expect(formats).toContain('avif');
        expect(formats).toContain('webp');
        
        // Verify we have exactly 2 modern formats
        expect(formats.length).toBe(2);
        
        // AVIF should come before WebP (more efficient format first)
        expect(formats.indexOf('avif')).toBeLessThan(formats.indexOf('webp'));
      }),
      { numRuns: 100 }
    );
  });

  it('should configure JPEG as fallback format for all images', () => {
    fc.assert(
      fc.property(imageArbitrary, () => {
        // The OptimizedImage component uses 'jpeg' as fallbackFormat
        // This will be used in the <img> element inside <picture>
        const fallbackFormat = 'jpeg';
        
        // Verify fallback format is JPEG (widely supported)
        expect(fallbackFormat).toBe('jpeg');
        
        // Verify fallback is a valid image format
        expect(['jpeg', 'jpg', 'png']).toContain(fallbackFormat);
      }),
      { numRuns: 100 }
    );
  });

  it('should ensure format fallback chain follows browser compatibility order', () => {
    fc.assert(
      fc.property(imageArbitrary, () => {
        // Format priority: AVIF (newest, best compression) -> WebP (good support) -> JPEG (universal)
        const formats = ['avif', 'webp'];
        const fallback = 'jpeg';
        
        // Verify the chain includes all three format types
        const fullChain = [...formats, fallback];
        expect(fullChain).toContain('avif');
        expect(fullChain).toContain('webp');
        expect(fullChain).toContain('jpeg');
        
        // Verify order: AVIF first (best compression)
        expect(fullChain[0]).toBe('avif');
        
        // WebP second (good compression, better support than AVIF)
        expect(fullChain[1]).toBe('webp');
        
        // JPEG last (universal support)
        expect(fullChain[2]).toBe('jpeg');
      }),
      { numRuns: 100 }
    );
  });

  it('should configure formats that cover all browser compatibility scenarios', () => {
    fc.assert(
      fc.property(
        fc.constantFrom('modern', 'recent', 'legacy'),
        (browserType) => {
          const formats = ['avif', 'webp'];
          const fallback = 'jpeg';
          
          // Modern browsers (Chrome 85+, Edge 85+): Support AVIF
          if (browserType === 'modern') {
            expect(formats).toContain('avif');
          }
          
          // Recent browsers (Chrome 23+, Firefox 65+, Safari 14+): Support WebP
          if (browserType === 'recent') {
            expect(formats).toContain('webp');
          }
          
          // Legacy browsers (IE, old Safari): Fall back to JPEG
          if (browserType === 'legacy') {
            expect(fallback).toBe('jpeg');
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should ensure format configuration is consistent across all image inputs', () => {
    fc.assert(
      fc.property(
        fc.array(imageArbitrary, { minLength: 1, maxLength: 10 }),
        (images) => {
          // For any set of images, the format configuration should be consistent
          const formats = ['avif', 'webp'];
          const fallback = 'jpeg';
          
          // All images will use the same format configuration
          images.forEach(() => {
            expect(formats).toEqual(['avif', 'webp']);
            expect(fallback).toBe('jpeg');
          });
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should configure formats that optimize for file size and quality', () => {
    fc.assert(
      fc.property(imageArbitrary, () => {
        const formats = ['avif', 'webp'];
        const fallback = 'jpeg';
        
        // AVIF provides best compression (30-50% smaller than JPEG)
        expect(formats[0]).toBe('avif');
        
        // WebP provides good compression (25-35% smaller than JPEG)
        expect(formats[1]).toBe('webp');
        
        // JPEG is the universal fallback
        expect(fallback).toBe('jpeg');
        
        // Verify all formats are valid image formats
        const allFormats = [...formats, fallback];
        allFormats.forEach(format => {
          expect(['avif', 'webp', 'jpeg', 'jpg', 'png']).toContain(format);
        });
      }),
      { numRuns: 100 }
    );
  });

  it('should ensure fallback format is always a widely supported format', () => {
    fc.assert(
      fc.property(imageArbitrary, () => {
        const fallback = 'jpeg';
        
        // Fallback must be JPEG or PNG (universal support)
        expect(['jpeg', 'jpg', 'png']).toContain(fallback);
        
        // Fallback should not be a modern format
        expect(['avif', 'webp']).not.toContain(fallback);
        
        // JPEG is preferred over PNG for photos (better compression)
        expect(fallback).toBe('jpeg');
      }),
      { numRuns: 100 }
    );
  });

  it('should configure format chain that maximizes compression while ensuring compatibility', () => {
    fc.assert(
      fc.property(imageArbitrary, () => {
        const formats = ['avif', 'webp'];
        const fallback = 'jpeg';
        const fullChain = [...formats, fallback];
        
        // Chain should have at least 3 formats (2 modern + 1 fallback)
        expect(fullChain.length).toBeGreaterThanOrEqual(3);
        
        // First format should be the most efficient (AVIF)
        expect(fullChain[0]).toBe('avif');
        
        // Last format should be the most compatible (JPEG)
        expect(fullChain[fullChain.length - 1]).toBe('jpeg');
        
        // All formats should be distinct
        const uniqueFormats = new Set(fullChain);
        expect(uniqueFormats.size).toBe(fullChain.length);
      }),
      { numRuns: 100 }
    );
  });

  it('should validate format configuration matches requirements for all image types', () => {
    fc.assert(
      fc.property(
        fc.record({
          format: fc.constantFrom('jpg', 'jpeg', 'png', 'gif'),
          width: fc.integer({ min: 100, max: 5000 }),
          height: fc.integer({ min: 100, max: 5000 })
        }),
        (imageInput) => {
          // Regardless of input format, output should follow the same fallback chain
          const outputFormats = ['avif', 'webp'];
          const fallback = 'jpeg';
          
          // Modern formats should always be in the output
          expect(outputFormats).toContain('avif');
          expect(outputFormats).toContain('webp');
          
          // Fallback should always be JPEG
          expect(fallback).toBe('jpeg');
          
          // The configuration should handle any input format
          // by converting to the standard fallback chain
          const hasCompleteChain = 
            outputFormats.includes('avif') && 
            outputFormats.includes('webp') &&
            fallback === 'jpeg';
          expect(hasCompleteChain).toBe(true);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should ensure format configuration supports progressive enhancement', () => {
    fc.assert(
      fc.property(imageArbitrary, () => {
        const formats = ['avif', 'webp'];
        const fallback = 'jpeg';
        
        // Progressive enhancement: browsers use the first format they support
        // Modern browsers will use AVIF (best)
        // Older browsers will skip to WebP (good)
        // Legacy browsers will use JPEG (compatible)
        
        // Verify the chain supports progressive enhancement
        expect(formats[0]).toBe('avif'); // Best option first
        expect(formats[formats.length - 1]).toBe('webp'); // Good option last in modern formats
        expect(fallback).toBe('jpeg'); // Safe fallback
        
        // Each format in the chain should be progressively more compatible
        // AVIF < WebP < JPEG (in terms of browser support)
        const compatibilityOrder = ['avif', 'webp', 'jpeg'];
        const actualOrder = [...formats, fallback];
        expect(actualOrder).toEqual(compatibilityOrder);
      }),
      { numRuns: 100 }
    );
  });
});
